import CommonSubPage from './CommonSubPage';

const pageComponentMap = {
  1: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
    5: CommonSubPage,
    6: CommonSubPage,
  },
  2: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
    5: CommonSubPage,
    6: CommonSubPage,
    7: CommonSubPage,
    8: CommonSubPage,
    9: CommonSubPage,
  },
  3: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
    5: CommonSubPage,
    6: CommonSubPage,
    7: CommonSubPage,
    8: CommonSubPage,
    9: CommonSubPage,
    10: CommonSubPage,
    11: CommonSubPage,
  },
  4: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
  },
  5: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
    5: CommonSubPage,
  },
  6: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
    5: CommonSubPage,
    6: CommonSubPage,
    7: CommonSubPage,
    8: CommonSubPage,
  },
  7: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
    5: CommonSubPage,
  },
  8: {
    1: CommonSubPage,
    2: CommonSubPage,
    3: CommonSubPage,
    4: CommonSubPage,
    5: CommonSubPage,
    6: CommonSubPage,
    7: CommonSubPage,
    8: CommonSubPage,
    9: CommonSubPage,
    10: CommonSubPage,
  },
};

export default pageComponentMap;
